Repository fluid-project/hearth, pull requests merged in 2022-07, with the labels that each got.

#143 feat: add controller, routes, and views for ResourceCollection model (resolves #142)
  composer.json
  stubs/app/Http/Controllers/ResourceCollectionController.php
  stubs/app/Http/Requests/CreateResourceCollectionRequest.php
  stubs/app/Http/Requests/DestroyResourceCollectionRequest.php
  stubs/app/Http/Requests/UpdateResourceCollectionRequest.php
  stubs/app/Models/ResourceCollection.php
  stubs/app/Policies/ResourceCollectionPolicy.php
  stubs/lang/en/resource-collection.php
  stubs/lang/fr/resource-collection.php
  stubs/resources/views/resource-collections/create.blade.php
  stubs/resources/views/resource-collections/edit.blade.php
  stubs/resources/views/resource-collections/index.blade.php
  stubs/resources/views/resource-collections/show.blade.php
  stubs/routes/resource-collections.php
  stubs/routes/web.php
  stubs/tests/Feature/ResourceCollectionTest.php
Labels: enhancement

#156 feat: switch from PHP CS Fixer to Pint (resolves #155)
  .github/workflows/pint.yml
  .php_cs.dist.php
  .pre-commit-config.yaml
  composer.json
  database/factories/InvitationFactory.php
  database/factories/OrganizationFactory.php
  resources/lang/en/nav.php
  resources/lang/fr/nav.php
  resources/lang/fr/passwords.php
  src/Commands/HearthCommand.php
  src/Components/Alert.php
  src/Components/Error.php
  src/Components/Hint.php
  src/Components/Label.php
  src/Components/LocaleSelect.php
  src/Components/Textarea.php
  src/HearthServiceProvider.php
  src/Traits/AriaDescribable.php
  src/Traits/GeneratesTranslatableFieldAttributes.php
  src/Traits/HandlesValidation.php
  src/Traits/HasMembers.php
  src/helpers.php
  stubs/app/Actions/Fortify/RedirectIfTwoFactorAuthenticatable.php
  stubs/app/Http/Controllers/InvitationController.php
  stubs/app/Http/Controllers/JoinController.php
  stubs/app/Http/Controllers/MembershipController.php
  stubs/app/Http/Controllers/OrganizationController.php
  stubs/app/Http/Middleware/RequirePassword.php
  stubs/app/Http/Requests/AcceptInvitationRequest.php
  stubs/app/Http/Requests/Auth/LoginRequest.php
  stubs/app/Http/Requests/CreateInvitationRequest.php
  stubs/app/Http/Requests/DestroyOrganizationRequest.php
  stubs/app/Http/Requests/DestroyResourceCollectionRequest.php
  stubs/app/Http/Requests/DestroyResourceRequest.php
  stubs/app/Http/Requests/DestroyUserRequest.php
  stubs/app/Http/Requests/UpdateMembershipRequest.php
  stubs/app/Http/Responses/FailedTwoFactorLoginResponse.php
  stubs/app/Models/Organization.php
  stubs/app/Models/Resource.php
  stubs/app/Models/ResourceCollection.php
  stubs/app/Models/User.php
  stubs/app/Policies/OrganizationPolicy.php
  stubs/app/Policies/ResourceCollectionPolicy.php
  stubs/app/Policies/ResourcePolicy.php
  stubs/app/Policies/UserPolicy.php
  stubs/app/Providers/FortifyServiceProvider.php
  stubs/app/Rules/NotLastAdmin.php
  stubs/routes/fortify.php
  stubs/routes/web.php
  stubs/tests/Feature/JoinTest.php
  stubs/tests/Feature/OrganizationTest.php
  stubs/tests/Feature/ResourceCollectionTest.php
  stubs/tests/Feature/ResourceTest.php
  tests/Feature/InvitationTest.php
  tests/Feature/JoinTest.php
  tests/Feature/MembershipTest.php
  tests/Feature/UserTest.php
  tests/Fixtures/TranslatableModel.php
Labels: enhancement

#160 chore(l10n): update translations
  stubs/lang/fr/resource-collection.php
Labels: localization

#163 feat: add standalone RadioButton component (resolves #145)
  resources/views/components/radio-button.blade.php
  src/Components/RadioButton.php
  src/HearthServiceProvider.php
  stubs/app/Http/Controllers/OrganizationController.php
  stubs/phpstan.neon.dist
  tests/Components/RadioButtonTest.php
Labels: enhancement

#164 fix: handle keyed validation errors (resolves #149)
  src/Traits/HandlesValidation.php
  tests/Components/CheckboxesTest.php
Labels: bug

#166 feat: support Markdown in hints (resolves #162)
  .github/workflows/integration.yml
  .github/workflows/lint-analyze.yml
  .github/workflows/pint.yml
  .github/workflows/run-tests.yml
  README.md
  composer.json
  resources/views/components/hint.blade.php
  tests/Components/HintTest.php
Labels: enhancement

#165 feat!: standardize options for checkboxes, radio buttons, and selects
  database/factories/OrganizationFactory.php
  database/factories/UserFactory.php
  resources/views/components/checkboxes.blade.php
  resources/views/components/radio-buttons.blade.php
  resources/views/components/select.blade.php
  src/Components/Checkboxes.php
  src/Components/DateInput.php
  src/Components/RadioButtons.php
  src/Components/Select.php
  src/helpers.php
  stubs/app/Http/Controllers/MembershipController.php
  stubs/app/Http/Controllers/OrganizationController.php
  tests/Components/CheckboxesTest.php
  tests/Components/RadioButtonsTest.php
  tests/Components/SelectTest.php
  tests/Unit/HelpersTest.php
Labels: enhancement

#168 fix: normalize ids to more standard characters
  resources/views/components/checkboxes.blade.php
  resources/views/components/radio-buttons.blade.php
  tests/Components/CheckboxesTest.php
  tests/Components/RadioButtonsTest.php
Labels: bug
